### ISSUE TITLE
Licence request

### ISSUE THREAD

**Issue by Sam-Rowe** [jgasteiz/home-consumption-dashboard#4]
Hi @jgasteiz 

This looks superb. I would love to contribute but I can't see a licence file? 

I want to enhance by mixing in the data from https://carbonintensity.org.uk/ api's to show a CO2 estimate for the day's consumption ( Given a region or at a nation level )

**Comment by jgasteiz** [comment]
Hey @Sam-Rowe , thanks for that. I've just added a License file.

That sounds like an excellent idea, I'll be happy to review any PRs that you throw my way, if that's what you were thinking about.

Cheers!

**Comment by Sam-Rowe** [comment]
Fantastic! thank you @jgasteiz
